{{- if .Values.crd.install -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumemanagers.kvc.kubeflow.org
spec:
  group: kvc.kubeflow.org
  names:
    kind: VolumeManager
    listKind: VolumeManagerList
    plural: volumemanagers
    singular: volumemanager
  scope: Namespaced
  version: v1
{{end}}
