apiVersion: v1
kind: Pod
metadata:
  name: kvc-claim-pod
spec:
  volumes:
    - name: dataset-claim
      persistentVolumeClaim:
        claimName: <insert-claim-name-here>
  containers:
  - image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 1d"]
    name: kvc-sleep
    volumeMounts:
    - mountPath: /var/data
      name: dataset-claim
