registry: "gcr.io/"
org: "constant-cubist-173123"
repo: "kube-volume-controller"
tag: "master"

## Flags used for kube-volume-controller command
## Example usage:
# flags:
# - "--namespace:<namespace>"
flags:
- "--podFile=./pkg/resources/pod.tmpl"
- "--pvFile=./pkg/resources/pv.tmpl"
- "--pvcFile=./pkg/resources/pvc.tmpl"
- "--namespace=kvc-testing"

## Install Default RBAC roles and bindings
rbac:
  install: true
  apiVersion: v1
